name: 'Build Orange Windows installers'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019
    env:
      # git repo from which to pull orange3 sources
      REPO: https://github.com/biolab/orange3.git
      # Branch/ref from which to pull
      BUILD_BRANCH: master
      # Commit ref/tag to checkout
      BUILD_COMMIT: FETCH_HEAD

      # Build the package locally or use the build packages from
      # conda-forge / PyPI. The BUILD_COMMIT must match the package version
      # to build.
      # Comment/override this if building release versions.
      BUILD_LOCAL: 1

      PIP_DISABLE_PIP_VERSION_CHECK: 1
      # build env dependencies for building orange3 wheels or any of its
      # dependencies that do not have wheels available
      BUILD_DEPS: wheel~=0.37.0 pip~=22.0.3

    strategy:
      fail-fast: False
      # Note the python version here refers to the one included in the installer
      # not the one used for building/packaging
      matrix:
        include:
          - PYTHON_VERSION: '3.9.12'
            PLATTAG: win_amd64
            CONDA: C:\Miniconda\Scripts\conda
            PYTHON: C:\Miniconda\python
            MINICONDA_VERSION: 'py39_4.12.0'
            CONDA_BUILD_VERSION: '3.22'
            CONDA_USE_ONLY_TAR_BZ2: ""
            CONDA_SPEC_FILE:
            # CONDA_SPEC_FILE: ..\specs\win\conda-spec.txt

          - PYTHON_VERSION: '3.9.13'
            PLATTAG: win_amd64
            ENVSPEC: ../specs/win/PY38.txt
            PYTHON: C:\Python39-x64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build script
        shell: cmd
        run: |
          git clone -q %REPO%
          cd orange3
          git fetch origin %BUILD_BRANCH%
          git checkout %BUILD_COMMIT%

          set "PATH=C:\msys64\usr\bin;C:\Program Files (x86)\NSIS;%PATH%"
          pacman -S --noconfirm zip unzip
          if not "%CONDA%" == "" ( rmdir /q /s "C:\Program Files (x86)\Windows Kits\10\include\wdf" )
          if not "%CONDA%" == "" ( ..\ci\appveyor-conda-build.bat )
          if "%CONDA%" == "" ( ..\ci\appveyor-build.bat )

      - name: Find installers
        shell: cmd
        run: |
          for %%s in ( orange3/dist/Orange3*.exe ) do ( 
            echo "INSTALLER=%%s"
            echo INSTALLER=%%s >> %GITHUB_ENV% 
          )

      - name: Test script
        shell: cmd
        run: |
          echo INSTALLER = %INSTALLER%
          :: cleanup registry of anaconda reg keys
          reg delete HKEY_LOCAL_MACHINE\Software\Python\ContinuumAnalytics /f || cd .
          reg delete HKEY_CURRENT_USER\Software\Python\ContinuumAnalytics /f || cd .
          dir orange3\dist
          :: Install in silent mode. Output has to be piped somewhere so the installer
          :: runs 'attached' to the console.
          orange3\dist\%INSTALLER% /S /D=C:\test-install > nul
          :: The venv and conda envs create different install layouts.
          if "%CONDA%" == "" ( set "PYTHON=C:\test-install\Scripts\python" )
          if not "%CONDA%" == "" ( set "PYTHON=C:\test-install\python" )
          ::if not "%CONDA%" == "" ( ci\appveyor-make-portable.bat C:\test-install %CD%\installers\Orange.zip )

          "%PYTHON%" --version
          "%PYTHON%" -m pip --version
          "%PYTHON%" -m pip list --format=freeze
          :: Test that orange and all dependencies are installed in a consistent state
          "%PYTHON%" -m pip install --no-index --no-cache-dir orange3

          :: Run test suite in the installed environment.
          set ORANGE_DEPRECATIONS_ERROR=1
          set PYTHONWARNINGS=module
          "%PYTHON%" -m unittest -v Orange.tests Orange.widgets.tests || cd .

          :: Log the filename and the sha checksum
          for /f %%s in ( 'sha256sum -b installers/%INSTALLER%' ) do ( set "CHECKSUM=%%s" )
          echo INSTALLER = %INSTALLER%
          echo SHA256    = %CHECKSUM%

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Installer
          path: orange3/dist/${{ env.INSTALLER }}
